// downloadPdf.js — client-side PDF generation using jsPDF
import { jsPDF } from "jspdf";

const GREEN  = [45, 122, 58];
const RED    = [192, 57, 43];
const DARK   = [15, 26, 16];
const MUTED  = [90, 122, 94];
const BORDER = [212, 232, 214];
const WHITE  = [255, 255, 255];

function addHeader(doc, title, subtitle, pageW) {
  // Green header bar
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageW, 22, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Dablin', 14, 14);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('dablin.co', pageW - 14, 14, { align: 'right' });

  // Title
  doc.setTextColor(...DARK);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 38);

  // Subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(subtitle, 14, 46);

  // Divider
  doc.setDrawColor(...BORDER);
  doc.line(14, 50, pageW - 14, 50);

  return 58; // y position after header
}

function addFooter(doc, pageW, pageH) {
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by Dablin · dablin.co · ${new Date().toLocaleDateString()}`, pageW / 2, pageH - 8, { align: 'center' });
}

function checkY(doc, y, pageH, pageW) {
  if (y > pageH - 24) {
    addFooter(doc, pageW, pageH);
    doc.addPage();
    return 20;
  }
  return y;
}

export function downloadVisibilityCheckPdf(result) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  let y = addHeader(doc, 'AI Visibility Check Report', `${result.url} · Brand: ${result.brand}`, pageW);

  // Summary boxes
  const engines = [
    { label: 'Claude',  count: result.mentionSummary.claude,  color: [198, 123, 47] },
    { label: 'GPT-4o',  count: result.mentionSummary.gpt,     color: [16, 163, 127] },
    { label: 'Gemini',  count: result.mentionSummary.gemini,  color: [66, 133, 244] },
  ];
  const total = result.queries.length;
  const boxW = (pageW - 28 - 8) / 3;
  engines.forEach((e, i) => {
    const x = 14 + i * (boxW + 4);
    doc.setFillColor(247, 251, 247);
    doc.setDrawColor(...BORDER);
    doc.roundedRect(x, y, boxW, 18, 2, 2, 'FD');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...e.color);
    doc.text(e.label, x + boxW / 2, y + 6, { align: 'center' });
    doc.setFontSize(14);
    doc.setTextColor(e.count > 0 ? GREEN : RED);
    doc.text(`${e.count}/${total}`, x + boxW / 2, y + 13, { align: 'center' });
  });
  y += 24;

  // Queries table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Query Results', 14, y);
  y += 6;

  // Table header
  doc.setFillColor(...GREEN);
  doc.rect(14, y, pageW - 28, 7, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Query', 16, y + 5);
  doc.text('Claude', pageW - 52, y + 5, { align: 'center' });
  doc.text('GPT-4o', pageW - 36, y + 5, { align: 'center' });
  doc.text('Gemini', pageW - 20, y + 5, { align: 'center' });
  y += 7;

  result.results.forEach((row, i) => {
    y = checkY(doc, y, pageH, pageW);
    const rowH = 8;
    doc.setFillColor(i % 2 === 0 ? 247 : 255, i % 2 === 0 ? 251 : 255, i % 2 === 0 ? 247 : 255);
    doc.rect(14, y, pageW - 28, rowH, 'F');
    doc.setDrawColor(...BORDER);
    doc.rect(14, y, pageW - 28, rowH, 'S');

    doc.setTextColor(...DARK);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const queryText = row.query.length > 60 ? row.query.substring(0, 57) + '...' : row.query;
    doc.text(queryText, 16, y + 5.5);

    [
      { val: row.claude.mentioned, x: pageW - 52 },
      { val: row.gpt.mentioned,    x: pageW - 36 },
      { val: row.gemini.mentioned, x: pageW - 20 },
    ].forEach(({ val, x }) => {
      doc.setTextColor(...(val ? GREEN : RED));
      doc.setFont('helvetica', 'bold');
      doc.text(val ? '✓' : '✗', x, y + 5.5, { align: 'center' });
    });
    y += rowH;
  });
  y += 8;

  // Competitors
  if (result.topCompetitors?.length > 0) {
    y = checkY(doc, y, pageH, pageW);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK);
    doc.text('Competitors Spotted in AI Responses', 14, y);
    y += 6;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    const compText = result.topCompetitors.map(c => `${c.name} (${c.count}×)`).join('  ·  ');
    const lines = doc.splitTextToSize(compText, pageW - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 4;
  }

  addFooter(doc, pageW, pageH);
  doc.save(`dablin-visibility-check-${result.brand}-${new Date().toISOString().split('T')[0]}.pdf`);
}

export function downloadAuditPdf(result, type) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const isAi = type === 'ai';
  const title = isAi ? 'AI Visibility Audit Report' : 'SEO Audit Report';

  const checks = result.checks || {};
  const issues = result.issues || {};
  const passed = Object.values(checks).filter(Boolean).length;
  const total  = Object.keys(checks).length;
  const score  = Math.round((passed / total) * 100);

  let y = addHeader(doc, title, result.url, pageW);

  // Score circle (simulated as box)
  const scoreColor = score >= 75 ? GREEN : score >= 50 ? [217, 119, 6] : RED;
  doc.setFillColor(247, 251, 247);
  doc.setDrawColor(...scoreColor);
  doc.roundedRect(14, y, 50, 24, 3, 3, 'FD');
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...scoreColor);
  doc.text(`${score}%`, 39, y + 13, { align: 'center' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(`${passed}/${total} checks passed`, 39, y + 20, { align: 'center' });

  // Status label
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  const statusLabel = score >= 75 ? 'Good' : score >= 50 ? 'Needs improvement' : 'Critical issues found';
  doc.text(statusLabel, 72, y + 10);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(`Audited on ${new Date().toLocaleDateString()}`, 72, y + 17);
  y += 30;

  // Checks table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Check Results', 14, y);
  y += 6;

  // Table header
  doc.setFillColor(...GREEN);
  doc.rect(14, y, pageW - 28, 7, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Check', 16, y + 5);
  doc.text('Status', pageW - 14, y + 5, { align: 'right' });
  y += 7;

  const LABELS = isAi ? {
    llmsTxt: 'llms.txt file', aiCrawlers: 'AI crawlers allowed',
    orgSchema: 'Organization schema', sameAs: 'sameAs links',
    siteName: 'WebSite schema', h1: 'Clear H1', metaDesc: 'Meta description',
    noAiBlock: 'No noai tag', canonical: 'Canonical URL',
    openGraph: 'Open Graph tags', speed: 'Fast response', https: 'HTTPS',
  } : {
    meta: 'Meta description', schema: 'Schema markup', alt: 'Image alt text',
    headings: 'Heading structure', wordCount: 'Word count', canonical: 'Canonical tag',
    robots: 'Robots tag', og: 'Open Graph tags', viewport: 'Mobile viewport',
    productSchema: 'Product schema', breadcrumb: 'Breadcrumb schema',
    reviewSchema: 'Review schema', internalLinks: 'Internal links',
  };

  Object.entries(checks).forEach(([key, p], i) => {
    y = checkY(doc, y, pageH, pageW);
    const rowH = p ? 8 : 14;
    doc.setFillColor(i % 2 === 0 ? 247 : 255, i % 2 === 0 ? 251 : 255, i % 2 === 0 ? 247 : 255);
    doc.rect(14, y, pageW - 28, rowH, 'F');
    doc.setDrawColor(...BORDER);
    doc.rect(14, y, pageW - 28, rowH, 'S');

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK);
    doc.text(LABELS[key] || key, 16, y + (p ? 5.5 : 4));

    if (!p && issues[key]) {
      doc.setFontSize(7);
      doc.setTextColor(...MUTED);
      const issueLines = doc.splitTextToSize(issues[key], pageW - 60);
      doc.text(issueLines[0], 16, y + 10);
    }

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...(p ? GREEN : RED));
    doc.text(p ? '✓ Pass' : '✗ Fail', pageW - 14, y + (p ? 5.5 : 4), { align: 'right' });
    y += rowH;
  });

  addFooter(doc, pageW, pageH);
  const slug = result.url.replace(/https?:\/\//, '').replace(/[^a-z0-9]/gi, '-').substring(0, 30);
  doc.save(`dablin-${type}-audit-${slug}-${new Date().toISOString().split('T')[0]}.pdf`);
}
