import { SignInButton, SignUpButton } from "@clerk/clerk-react";
import { trackEvent } from "../analytics";
import { useState, useEffect, useRef } from "react";

function FaqItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`faq-item ${open ? 'open' : ''}`} onClick={() => setOpen(!open)}>
      <div className="faq-question">
        <span>{q}</span>
        <span className="faq-icon">{open ? '−' : '+'}</span>
      </div>
      {open && <div className="faq-answer">{a}</div>}
    </div>
  );
}

const FEATURES = [
  {
    title: "AI description generator",
    desc: "Paste your product specs — get an SEO-ready title, meta description, feature bullets, Shopify tags, and full HTML in seconds.",
  },
  {
    title: "13-point SEO audit",
    desc: "Paste any product page URL. Dablin checks meta tags, headings, schema, Open Graph, canonical, robots, and more — with AI fixes.",
  },
  {
    title: "AI Visibility audit",
    desc: "Check if ChatGPT, Perplexity and Gemini can find and understand your page. 12 checks including llms.txt, schema, and AI crawler access.",
  },
  {
    title: "AI-generated fixes for every issue",
    desc: "Every failed check comes with a ready-to-copy code fix generated by AI. No guesswork, no developer needed.",
  },
  {
    title: "Multi-platform ready",
    desc: "Shopify, Amazon, WooCommerce. Descriptions and audits work on any e-commerce platform.",
  },
  {
    title: "Pay per use, credits never expire",
    desc: "No subscription. Buy credits once, use them across all three tools whenever you need them.",
  },
];

const PRICING = [
  {
    name: "Try it free",
    price: "€0",
    credits: "7 credits",
    desc: "No credit card needed — 7 free credits",
    cta: "Start free",
    highlight: false,
    features: ["7 credits", "All categories", "SEO score", "HTML export"],
  },
  {
    name: "Starter",
    price: "€3",
    credits: "20 credits",
    desc: "One-time, no subscription",
    cta: "Get started",
    highlight: true,
    features: ["20 AI descriptions", "4 SEO or AI audits", "All categories", "SEO score", "HTML export", "History"],
  },
  {
    name: "Pro",
    price: "€12",
    credits: "100 credits",
    desc: "One-time, no subscription",
    cta: "Go Pro",
    highlight: false,
    features: ["100 AI descriptions", "20 SEO or AI audits", "All categories", "SEO score", "HTML export", "History"],
  },
  {
    name: "Studio",
    price: "€49",
    credits: "500 credits",
    desc: "Best value for agencies",
    cta: "Get Studio",
    highlight: false,
    features: ["500 AI descriptions", "100 SEO or AI audits", "All categories", "SEO score", "HTML export", "History", "Priority support"],
  },
];

const FAQ = [
  {
    q: "What is Dablin?",
    a: "Dablin is the only e-commerce tool that combines AI brand visibility checking, AI visibility auditing, SEO auditing, and product description generation in one place. It tells you if ChatGPT, Gemini, and Claude mention your brand — and helps you fix what's stopping them.",
  },
  {
    q: "Does ChatGPT mention my store?",
    a: "Most stores are invisible to AI engines. Dablin's AI Visibility Check queries Claude, GPT-4o, and Gemini with 5 variations of your category searches and shows you exactly which AI engines mention your brand — and which competitors they recommend instead.",
  },
  {
    q: "What is an AI Visibility Audit?",
    a: "It's a 12-point technical check that finds why AI engines can't find or understand your page. It checks for llms.txt, AI crawler access, Organization schema, sameAs links, HTTPS, response speed, Open Graph tags, and more — with a ready-to-copy fix for every issue.",
  },
  {
    q: "What does the SEO Audit check?",
    a: "13 checks across content quality (meta description, headings, word count, image alt text), technical SEO (canonical, robots, viewport, Open Graph), structured data (Product schema, BreadcrumbList, reviews), and link structure — each with an AI-generated fix.",
  },
  {
    q: "How many credits does each tool use?",
    a: "1 credit per description · 5 credits per SEO Audit · 5 credits per AI Visibility Audit · 7 credits per AI Visibility Check. New accounts get 7 free credits — enough for one full AI Visibility Check.",
  },
  {
    q: "What platforms does it support?",
    a: "Description generation works for Shopify, Amazon, and WooCommerce. All audits work on any publicly accessible URL.",
  },
  {
    q: "How is it different from ChatGPT?",
    a: "ChatGPT can't tell you if it mentions your brand, audit your pages, or generate SEO-scored descriptions with correct character limits. Dablin does all of this in one tool, purpose-built for e-commerce.",
  },
  {
    q: "How does the credit system work?",
    a: "Credits are shared across all four tools. Buy once in one-time packs — no subscription, no monthly fees, credits never expire.",
  },
];

// ── HERO DEMOS ──────────────────────────────────────────────────────────────

function typeText(text, setText, onDone, speed = 28) {
  let i = 0;
  setText('');
  const iv = setInterval(() => {
    i++;
    setText(text.slice(0, i));
    if (i >= text.length) { clearInterval(iv); onDone && onDone(); }
  }, speed);
  return iv;
}

function GeneratorDemo() {
  const [phase, setPhase] = useState('idle');
  const [val1, setVal1] = useState('');
  const [val2, setVal2] = useState('');
  const [visibleFields, setVisibleFields] = useState(0);
  const [dots, setDots] = useState('');
  const timerRef = useRef(null);

  useEffect(() => {
    const t = setTimeout(() => runDemo(), 600);
    return () => { clearTimeout(t); clearTimeout(timerRef.current); };
  }, []);

  function runDemo() {
    setPhase('typing1'); setVal1(''); setVal2(''); setVisibleFields(0);
    typeText('Bamboo Cutting Board Set', setVal1, () => {
      setTimeout(() => {
        setPhase('typing2');
        typeText('3-piece, organic bamboo, juice grooves, non-slip feet, dishwasher safe', setVal2, () => {
          setTimeout(() => {
            setPhase('generating');
            let d = 0;
            const iv = setInterval(() => { d = (d + 1) % 4; setDots('.'.repeat(d)); }, 400);
            timerRef.current = setTimeout(() => {
              clearInterval(iv);
              setPhase('output');
              let f = 0;
              const fiv = setInterval(() => {
                f++; setVisibleFields(f);
                if (f >= 4) { clearInterval(fiv); timerRef.current = setTimeout(() => runDemo(), 4000); }
              }, 500);
            }, 2000);
          }, 600);
        }, 18);
      }, 400);
    }, 38);
  }

  return (
    <div style={{ borderRadius: '14px', border: '1px solid var(--border)', background: 'var(--off-white)', overflow: 'hidden', boxShadow: '0 8px 40px rgba(45,122,58,0.10)' }}>
      <div style={{ background: '#e8f5ea', padding: '9px 14px', display: 'flex', alignItems: 'center', gap: '7px', borderBottom: '1px solid var(--border)' }}>
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#ff5f57', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#febc2e', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#28c840', display: 'inline-block' }} />
        <span style={{ flex: 1, textAlign: 'center', fontSize: '11px', color: 'var(--muted)' }}>dablin.co · Generate</span>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', minHeight: '280px' }}>
        <div style={{ padding: '20px', borderRight: '1px solid var(--border)', background: 'white' }}>
          <div style={{ fontSize: '10px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', color: 'var(--muted)', marginBottom: '14px' }}>Product Details</div>
          <div style={{ marginBottom: '12px' }}>
            <div style={{ fontSize: '10px', fontWeight: '600', color: 'var(--muted)', marginBottom: '4px' }}>PRODUCT NAME</div>
            <div style={{ background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '6px', padding: '7px 10px', fontSize: '12px', color: 'var(--text)', minHeight: '30px' }}>
              {val1}{phase === 'typing1' ? <span style={{ borderRight: '2px solid var(--green)', animation: 'blink 0.8s infinite' }}>&nbsp;</span> : ''}
            </div>
          </div>
          <div style={{ marginBottom: '14px' }}>
            <div style={{ fontSize: '10px', fontWeight: '600', color: 'var(--muted)', marginBottom: '4px' }}>KEY FEATURES</div>
            <div style={{ background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '6px', padding: '7px 10px', fontSize: '12px', color: 'var(--text)', minHeight: '52px', lineHeight: '1.5' }}>
              {val2}{phase === 'typing2' ? <span style={{ borderRight: '2px solid var(--green)' }}>&nbsp;</span> : ''}
            </div>
          </div>
          <button style={{ width: '100%', padding: '9px', borderRadius: '7px', border: 'none', fontSize: '12px', fontWeight: '700', cursor: 'default', background: (phase === 'generating' || phase === 'output') ? 'var(--green)' : '#b0c9b4', color: 'white', transition: 'background 0.4s' }}>
            {phase === 'generating' ? `✦ Generating${dots}` : '✦ Generate Description'}
          </button>
        </div>
        <div style={{ padding: '20px', background: 'var(--off-white)' }}>
          <div style={{ fontSize: '10px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', color: 'var(--muted)', marginBottom: '14px' }}>Generated Output</div>
          {(phase === 'idle' || phase === 'typing1' || phase === 'typing2') && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', color: 'var(--muted)', fontSize: '12px', gap: '8px' }}>
              <div style={{ fontSize: '20px', color: 'var(--green-mid)' }}>✦</div>
              <div>Output will appear here</div>
            </div>
          )}
          {phase === 'generating' && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', gap: '10px' }}>
              <div style={{ fontSize: '20px', color: 'var(--green)', animation: 'spin 1.2s linear infinite' }}>✦</div>
              <div style={{ fontSize: '12px', color: 'var(--muted)' }}>Writing description{dots}</div>
            </div>
          )}
          {phase === 'output' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {visibleFields >= 1 && <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: '7px', padding: '9px 11px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
                  <span style={{ fontSize: '9px', fontWeight: '700', color: 'var(--green)', letterSpacing: '0.8px' }}>PRODUCT TITLE</span>
                  <span style={{ fontSize: '9px', color: 'var(--green)', fontWeight: '600' }}>56/70</span>
                </div>
                <div style={{ fontSize: '11px', color: 'var(--text)', lineHeight: '1.4' }}>GreenKitchen Bamboo Cutting Board Set | Non-Slip, 3-Piece</div>
              </div>}
              {visibleFields >= 2 && <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: '7px', padding: '9px 11px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
                  <span style={{ fontSize: '9px', fontWeight: '700', color: 'var(--green)', letterSpacing: '0.8px' }}>META DESCRIPTION</span>
                  <span style={{ fontSize: '9px', color: 'var(--green)', fontWeight: '600' }}>114/155</span>
                </div>
                <div style={{ fontSize: '11px', color: 'var(--text)', lineHeight: '1.4' }}>Organic bamboo cutting board set — 3 sizes, juice grooves, non-slip feet. Dishwasher safe.</div>
              </div>}
              {visibleFields >= 3 && <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: '7px', padding: '9px 11px' }}>
                <span style={{ fontSize: '9px', fontWeight: '700', color: 'var(--green)', letterSpacing: '0.8px', display: 'block', marginBottom: '5px' }}>FEATURE BULLETS</span>
                <ul style={{ margin: 0, padding: '0 0 0 12px' }}>
                  {['Organic bamboo — sustainable', 'Juice grooves prevent mess', 'Non-slip feet, dishwasher safe'].map((b, i) => <li key={i} style={{ fontSize: '10px', color: 'var(--text)', lineHeight: '1.5' }}>{b}</li>)}
                </ul>
              </div>}
              {visibleFields >= 4 && <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: '7px', padding: '9px 11px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span style={{ fontSize: '9px', fontWeight: '700', color: 'var(--green)', letterSpacing: '0.8px' }}>SEO SCORE</span>
                <div style={{ flex: 1, height: '5px', background: 'var(--border)', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{ height: '100%', width: '92%', background: 'var(--green)', borderRadius: '3px' }} />
                </div>
                <span style={{ fontSize: '12px', fontWeight: '800', color: 'var(--green)' }}>92</span>
              </div>}
            </div>
          )}
        </div>
      </div>
      <style>{`@keyframes blink{0%,100%{opacity:1}50%{opacity:0}}@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}

function SeoAuditDemo() {
  const [phase, setPhase] = useState('idle');
  const [urlVal, setUrlVal] = useState('');
  const [showScore, setShowScore] = useState(false);
  const [visibleChecks, setVisibleChecks] = useState(0);
  const [dots, setDots] = useState('');
  const timerRef = useRef(null);

  useEffect(() => {
    const t = setTimeout(() => runDemo(), 600);
    return () => { clearTimeout(t); clearTimeout(timerRef.current); };
  }, []);

  function runDemo() {
    setPhase('typing'); setUrlVal(''); setShowScore(false); setVisibleChecks(0);
    typeText('https://mystore.com/products/bamboo-set', setUrlVal, () => {
      setTimeout(() => {
        setPhase('auditing');
        let d = 0;
        const iv = setInterval(() => { d = (d + 1) % 4; setDots('.'.repeat(d)); }, 400);
        timerRef.current = setTimeout(() => {
          clearInterval(iv);
          setPhase('results');
          setShowScore(true);
          let c = 0;
          const civ = setInterval(() => {
            c++; setVisibleChecks(c);
            if (c >= 5) { clearInterval(civ); timerRef.current = setTimeout(() => runDemo(), 4000); }
          }, 400);
        }, 2200);
      }, 500);
    }, 22);
  }

  const checks = [
    { label: 'Meta description', pass: true },
    { label: 'Heading structure', pass: true },
    { label: 'Product schema', pass: false, issue: 'No Product schema — missing Google Shopping' },
    { label: 'Open Graph tags', pass: false, issue: 'Missing og:image tag' },
    { label: 'Internal links', pass: true },
  ];

  return (
    <div style={{ borderRadius: '14px', border: '1px solid var(--border)', background: 'var(--off-white)', overflow: 'hidden', boxShadow: '0 8px 40px rgba(45,122,58,0.10)' }}>
      <div style={{ background: '#e8f5ea', padding: '9px 14px', display: 'flex', alignItems: 'center', gap: '7px', borderBottom: '1px solid var(--border)' }}>
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#ff5f57', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#febc2e', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#28c840', display: 'inline-block' }} />
        <span style={{ flex: 1, textAlign: 'center', fontSize: '11px', color: 'var(--muted)' }}>dablin.co · SEO Audit</span>
      </div>
      <div style={{ padding: '20px', background: 'white', minHeight: '300px' }}>
        <div style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
          <div style={{ flex: 1, background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '6px', padding: '8px 12px', fontSize: '12px', color: 'var(--text)', fontFamily: 'monospace' }}>
            {urlVal}{phase === 'typing' ? <span style={{ borderRight: '2px solid var(--green)', animation: 'blink 0.8s infinite' }}>&nbsp;</span> : ''}
          </div>
          <button style={{ background: (phase === 'auditing' || phase === 'results') ? 'var(--green)' : '#b0c9b4', color: 'white', border: 'none', borderRadius: '6px', padding: '8px 16px', fontSize: '12px', fontWeight: '700', cursor: 'default', whiteSpace: 'nowrap' }}>
            {phase === 'auditing' ? `Auditing${dots}` : 'Audit SEO'}
          </button>
        </div>
        {showScore && (
          <div style={{ background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '10px', padding: '16px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '52px', height: '52px', borderRadius: '50%', border: '3px solid #d97706', background: '#fff8e1', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '800', fontSize: '14px', color: '#d97706', flexShrink: 0 }}>62%</div>
            <div>
              <div style={{ fontWeight: '700', fontSize: '14px', color: 'var(--dark)', marginBottom: '2px' }}>Needs improvement</div>
              <div style={{ fontSize: '12px', color: 'var(--muted)' }}>8 of 13 checks passed</div>
            </div>
          </div>
        )}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {checks.slice(0, visibleChecks).map((c, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', padding: '10px 12px', background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '8px' }}>
              <span style={{ fontSize: '13px', flexShrink: 0 }}>{c.pass ? '✅' : '❌'}</span>
              <div>
                <div style={{ fontSize: '12px', fontWeight: '600', color: 'var(--dark)' }}>{c.label}</div>
                {!c.pass && <div style={{ fontSize: '11px', color: '#c0392b', marginTop: '2px' }}>{c.issue}</div>}
                {!c.pass && <div style={{ marginTop: '6px', background: '#f0faf1', border: '1px solid #b7debb', borderRadius: '5px', padding: '6px 8px', fontSize: '10px', color: 'var(--green)', fontWeight: '700' }}>✦ AI Fix available — copy & paste</div>}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function AiVisibilityDemo() {
  const [phase, setPhase] = useState('idle');
  const [urlVal, setUrlVal] = useState('');
  const [showScore, setShowScore] = useState(false);
  const [visibleChecks, setVisibleChecks] = useState(0);
  const [dots, setDots] = useState('');
  const timerRef = useRef(null);

  useEffect(() => {
    const t = setTimeout(() => runDemo(), 600);
    return () => { clearTimeout(t); clearTimeout(timerRef.current); };
  }, []);

  function runDemo() {
    setPhase('typing'); setUrlVal(''); setShowScore(false); setVisibleChecks(0);
    typeText('https://mystore.com/products/bamboo-set', setUrlVal, () => {
      setTimeout(() => {
        setPhase('auditing');
        let d = 0;
        const iv = setInterval(() => { d = (d + 1) % 4; setDots('.'.repeat(d)); }, 400);
        timerRef.current = setTimeout(() => {
          clearInterval(iv);
          setPhase('results');
          setShowScore(true);
          let c = 0;
          const civ = setInterval(() => {
            c++; setVisibleChecks(c);
            if (c >= 5) { clearInterval(civ); timerRef.current = setTimeout(() => runDemo(), 4000); }
          }, 400);
        }, 2200);
      }, 500);
    }, 22);
  }

  const checks = [
    { label: 'llms.txt file', pass: false, issue: 'No llms.txt — AI engines can\'t identify your site' },
    { label: 'AI crawlers allowed', pass: true },
    { label: 'Organization schema', pass: false, issue: 'No Organization schema — brand identity unclear' },
    { label: 'HTTPS', pass: true },
    { label: 'Open Graph tags', pass: true },
  ];

  return (
    <div style={{ borderRadius: '14px', border: '1px solid var(--border)', background: 'var(--off-white)', overflow: 'hidden', boxShadow: '0 8px 40px rgba(45,122,58,0.10)' }}>
      <div style={{ background: '#e8f5ea', padding: '9px 14px', display: 'flex', alignItems: 'center', gap: '7px', borderBottom: '1px solid var(--border)' }}>
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#ff5f57', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#febc2e', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#28c840', display: 'inline-block' }} />
        <span style={{ flex: 1, textAlign: 'center', fontSize: '11px', color: 'var(--muted)' }}>dablin.co · AI Visibility Audit</span>
      </div>
      <div style={{ padding: '20px', background: 'white', minHeight: '300px' }}>
        <div style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
          <div style={{ flex: 1, background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '6px', padding: '8px 12px', fontSize: '12px', color: 'var(--text)', fontFamily: 'monospace' }}>
            {urlVal}{phase === 'typing' ? <span style={{ borderRight: '2px solid var(--green)', animation: 'blink 0.8s infinite' }}>&nbsp;</span> : ''}
          </div>
          <button style={{ background: (phase === 'auditing' || phase === 'results') ? 'var(--green)' : '#b0c9b4', color: 'white', border: 'none', borderRadius: '6px', padding: '8px 16px', fontSize: '12px', fontWeight: '700', cursor: 'default', whiteSpace: 'nowrap' }}>
            {phase === 'auditing' ? `Auditing${dots}` : 'Run AI Audit'}
          </button>
        </div>
        {showScore && (
          <div style={{ background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '10px', padding: '16px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '52px', height: '52px', borderRadius: '50%', border: '3px solid #d97706', background: '#fff8e1', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '800', fontSize: '14px', color: '#d97706', flexShrink: 0 }}>58%</div>
            <div>
              <div style={{ fontWeight: '700', fontSize: '14px', color: 'var(--dark)', marginBottom: '2px' }}>Poor AI visibility</div>
              <div style={{ fontSize: '12px', color: 'var(--muted)' }}>7 of 12 checks passed</div>
            </div>
          </div>
        )}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {checks.slice(0, visibleChecks).map((c, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', padding: '10px 12px', background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '8px' }}>
              <span style={{ fontSize: '13px', flexShrink: 0 }}>{c.pass ? '✅' : '❌'}</span>
              <div>
                <div style={{ fontSize: '12px', fontWeight: '600', color: 'var(--dark)' }}>{c.label}</div>
                {!c.pass && <div style={{ fontSize: '11px', color: '#c0392b', marginTop: '2px' }}>{c.issue}</div>}
                {!c.pass && <div style={{ marginTop: '6px', background: '#f0faf1', border: '1px solid #b7debb', borderRadius: '5px', padding: '6px 8px', fontSize: '10px', color: 'var(--green)', fontWeight: '700' }}>✦ AI Fix available — copy & paste</div>}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function AiCheckDemo() {
  const [phase, setPhase] = useState('idle');
  const [urlVal, setUrlVal] = useState('');
  const [showResults, setShowResults] = useState(false);
  const [visibleRows, setVisibleRows] = useState(0);
  const [dots, setDots] = useState('');
  const timerRef = useRef(null);

  useEffect(() => {
    const t = setTimeout(() => runDemo(), 600);
    return () => { clearTimeout(t); clearTimeout(timerRef.current); };
  }, []);

  function runDemo() {
    setPhase('typing'); setUrlVal(''); setShowResults(false); setVisibleRows(0);
    typeText('https://mystore.com', setUrlVal, () => {
      setTimeout(() => {
        setPhase('checking');
        let d = 0;
        const iv = setInterval(() => { d = (d + 1) % 4; setDots('.'.repeat(d)); }, 400);
        timerRef.current = setTimeout(() => {
          clearInterval(iv);
          setPhase('results');
          setShowResults(true);
          let r = 0;
          const riv = setInterval(() => {
            r++; setVisibleRows(r);
            if (r >= 5) { clearInterval(riv); timerRef.current = setTimeout(() => runDemo(), 4000); }
          }, 450);
        }, 2400);
      }, 500);
    }, 22);
  }

  const rows = [
    { query: 'digital loyalty card program for cafés', claude: false, gpt: false, gemini: false, competitors: ['Stamp Me', 'Loopy'] },
    { query: 'replace paper stamp cards with digital', claude: false, gpt: true, gemini: false, competitors: ['Loopy', 'Punchh'] },
    { query: 'mobile wallet loyalty program software', claude: false, gpt: false, gemini: true, competitors: ['Yotpo', 'Stamp Me'] },
    { query: 'free digital rewards card for restaurants', claude: false, gpt: false, gemini: false, competitors: ['Loopy', 'Thanx'] },
    { query: 'Apple Wallet loyalty card for small business', claude: true, gpt: false, gemini: false, competitors: ['Stocard', 'Loopy'] },
  ];

  const mentionColor = (v) => v ? '#2d7a3a' : '#c0392b';

  return (
    <div style={{ borderRadius: '14px', border: '1px solid var(--border)', background: 'var(--off-white)', overflow: 'hidden', boxShadow: '0 8px 40px rgba(45,122,58,0.10)' }}>
      <div style={{ background: '#e8f5ea', padding: '9px 14px', display: 'flex', alignItems: 'center', gap: '7px', borderBottom: '1px solid var(--border)' }}>
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#ff5f57', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#febc2e', display: 'inline-block' }} />
        <span style={{ width: 9, height: 9, borderRadius: '50%', background: '#28c840', display: 'inline-block' }} />
        <span style={{ flex: 1, textAlign: 'center', fontSize: '11px', color: 'var(--muted)' }}>dablin.co · AI Visibility Check</span>
      </div>
      <div style={{ padding: '20px', background: 'white', minHeight: '300px' }}>
        <div style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
          <div style={{ flex: 1, background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '6px', padding: '8px 12px', fontSize: '12px', color: 'var(--text)', fontFamily: 'monospace' }}>
            {urlVal}{phase === 'typing' ? <span style={{ borderRight: '2px solid var(--green)', animation: 'blink 0.8s infinite' }}>&nbsp;</span> : ''}
          </div>
          <button style={{ background: (phase === 'checking' || phase === 'results') ? 'var(--green)' : '#b0c9b4', color: 'white', border: 'none', borderRadius: '6px', padding: '8px 14px', fontSize: '11px', fontWeight: '700', cursor: 'default', whiteSpace: 'nowrap' }}>
            {phase === 'checking' ? `Checking${dots}` : 'Check Visibility'}
          </button>
        </div>
        {showResults && (
          <>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '8px', marginBottom: '16px' }}>
              {[{ label: 'Claude', count: 1, color: '#c67b2f' }, { label: 'GPT-4o', count: 1, color: '#10a37f' }, { label: 'Gemini', count: 1, color: '#4285f4' }].map(e => (
                <div key={e.label} style={{ background: 'var(--off-white)', border: '1px solid var(--border)', borderRadius: '8px', padding: '10px', textAlign: 'center' }}>
                  <div style={{ fontSize: '10px', fontWeight: '700', color: e.color, textTransform: 'uppercase', letterSpacing: '0.5px' }}>{e.label}</div>
                  <div style={{ fontSize: '18px', fontWeight: '800', color: '#2d7a3a', fontFamily: "'Roboto Condensed', sans-serif" }}>1/5</div>
                  <div style={{ fontSize: '10px', color: 'var(--muted)' }}>queries mentioned</div>
                </div>
              ))}
            </div>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px' }}>
              <thead>
                <tr style={{ borderBottom: '2px solid var(--border)' }}>
                  <th style={{ textAlign: 'left', padding: '6px 8px', color: 'var(--muted)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Query</th>
                  <th style={{ textAlign: 'center', padding: '6px 4px', color: '#c67b2f', fontWeight: '700' }}>Claude</th>
                  <th style={{ textAlign: 'center', padding: '6px 4px', color: '#10a37f', fontWeight: '700' }}>GPT</th>
                  <th style={{ textAlign: 'center', padding: '6px 4px', color: '#4285f4', fontWeight: '700' }}>Gemini</th>
                </tr>
              </thead>
              <tbody>
                {rows.slice(0, visibleRows).map((r, i) => (
                  <tr key={i} style={{ borderBottom: '1px solid #eef5ef' }}>
                    <td style={{ padding: '7px 8px', color: 'var(--text)', lineHeight: '1.3' }}>
                      <div>{r.query}</div>
                      <div style={{ display: 'flex', gap: '4px', marginTop: '3px', flexWrap: 'wrap' }}>
                        {r.competitors.map(c => <span key={c} style={{ fontSize: '9px', background: '#f0faf1', border: '1px solid #c8e6cb', borderRadius: '100px', padding: '1px 6px', color: '#2d7a3a' }}>{c}</span>)}
                      </div>
                    </td>
                    <td style={{ textAlign: 'center', fontWeight: '700', fontSize: '13px', color: mentionColor(r.claude) }}>{ r.claude ? '✓' : '✗' }</td>
                    <td style={{ textAlign: 'center', fontWeight: '700', fontSize: '13px', color: mentionColor(r.gpt) }}>{ r.gpt ? '✓' : '✗' }</td>
                    <td style={{ textAlign: 'center', fontWeight: '700', fontSize: '13px', color: mentionColor(r.gemini) }}>{ r.gemini ? '✓' : '✗' }</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}
        {!showResults && phase !== 'results' && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', gap: '10px' }}>
            {phase === 'checking'
              ? <><div style={{ fontSize: '20px', color: 'var(--green)', animation: 'spin 1.2s linear infinite' }}>◎</div><div style={{ fontSize: '12px', color: 'var(--muted)' }}>Querying Claude, GPT-4o & Gemini{dots}</div></>
              : <><div style={{ fontSize: '20px', color: 'var(--green-mid)' }}>◎</div><div style={{ fontSize: '12px', color: 'var(--muted)' }}>Enter your URL above</div></>
            }
          </div>
        )}
      </div>
    </div>
  );
}

const HERO_TABS = [
  { id: 'aicheck',  label: '◎ AI Visibility Check', component: AiCheckDemo },
  { id: 'ai',       label: '◎ AI Visibility Audit',  component: AiVisibilityDemo },
  { id: 'seo',      label: '⌕ SEO Audit',            component: SeoAuditDemo },
  { id: 'generate', label: '✦ Generate',              component: GeneratorDemo },
];

function HeroDemoTabs() {
  const [active, setActive] = useState('aicheck');
  const ActiveDemo = HERO_TABS.find(t => t.id === active).component;
  return (
    <div style={{ maxWidth: '860px', margin: '0 auto' }}>
      <div style={{ display: 'flex', gap: '8px', justifyContent: 'center', marginBottom: '20px', flexWrap: 'wrap' }}>
        {HERO_TABS.map(t => (
          <button key={t.id} onClick={() => setActive(t.id)} style={{
            padding: '8px 16px', borderRadius: '100px', border: active === t.id ? '2px solid var(--green)' : '2px solid var(--border)',
            background: active === t.id ? 'var(--green)' : 'white', color: active === t.id ? 'white' : 'var(--muted)',
            fontFamily: "'Roboto', sans-serif", fontSize: '13px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.2s',
          }}>{t.label}</button>
        ))}
      </div>
      <ActiveDemo key={active} />
    </div>
  );
}

// ── TOOL TABS ───────────────────────────────────────────────────────────────

const TOOL_TABS = [
  {
    id: "generator",
    label: "✦ AI Description Generator",
    credit: "1 credit per generation",
    screenshot: "/Generator.png",
    bullets: [
      "Generates platform-ready title, meta description, and feature bullets",
      "Full HTML output — paste directly into Shopify, Amazon, or WooCommerce",
      "Built-in SEO score: title length, meta length, keyword presence",
      "10 product categories, 4 tones, supports any language",
    ],
  },
  {
    id: "audit",
    label: "⌕ SEO Audit",
    credit: "5 credits per audit",
    screenshot: "/SEO_Audit.png",
    bullets: [
      "13-point SEO check: meta tags, headings, word count, image alt text",
      "Technical SEO: canonical, robots, viewport, Open Graph tags",
      "Structured data: Product schema, BreadcrumbList, reviews",
      "AI-generated fix for every failed check — ready to copy and paste",
    ],
  },
  {
    screenshot: "/AI_Visibility_audit.png",
    bullets: [
      "12 checks for AI engine visibility: llms.txt, AI crawler access, HTTPS",
      "Brand identity: Organization schema, sameAs links, WebSite name",
      "AI-readable content: H1, meta description, canonical, Open Graph",
      "AI-generated fix for every failed check — ready to copy and paste",
    ],
  },
];

function ToolTabs() {
  const [active, setActive] = useState("generator");
  const tab = TOOL_TABS.find(t => t.id === active);
  return (
    <div style={{ background: 'var(--green-pale)', borderTop: '1px solid var(--green-mid)', borderBottom: '1px solid var(--green-mid)', padding: 'clamp(32px, 5vw, 56px) clamp(20px, 4vw, 48px)' }}>
      <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
        <div style={{ display: 'flex', gap: '10px', justifyContent: 'center', marginBottom: '40px', flexWrap: 'wrap' }}>
          {TOOL_TABS.map(t => (
            <button key={t.id} onClick={() => setActive(t.id)} style={{
              padding: '11px 24px', borderRadius: '100px',
              border: active === t.id ? '2px solid var(--green)' : '2px solid var(--green-mid)',
              background: active === t.id ? 'var(--green)' : 'white',
              color: active === t.id ? 'white' : 'var(--dark)',
              fontFamily: "'Roboto', sans-serif", fontSize: '14px', fontWeight: '600',
              cursor: 'pointer', transition: 'all 0.2s',
            }}>{t.label}</button>
          ))}
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '40px', alignItems: 'center' }}>
          <div style={{ borderRadius: '14px', overflow: 'hidden', border: '1px solid var(--green-mid)', boxShadow: '0 8px 40px rgba(45,122,58,0.12)' }}>
            <img src={tab.screenshot} alt={tab.label} style={{ width: '100%', display: 'block' }} />
          </div>
          <div>
            <div style={{ display: 'inline-block', background: 'var(--green)', color: 'white', fontSize: '12px', fontWeight: '700', padding: '4px 14px', borderRadius: '100px', marginBottom: '20px', letterSpacing: '0.5px' }}>
              {tab.credit}
            </div>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {tab.bullets.map((b, i) => (
                <li key={i} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', fontSize: '15px', color: 'var(--text)', lineHeight: '1.55' }}>
                  <span style={{ color: 'var(--green)', fontWeight: '700', fontSize: '14px', marginTop: '2px', flexShrink: 0 }}>✓</span>
                  {b}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── MAIN LANDING ─────────────────────────────────────────────────────────────

const NAV_ITEMS = [
  { href: "/ai-visibility-check", icon: "◎", label: "AI Visibility Check", desc: "See if ChatGPT, Gemini & Claude mention you" },
  { href: "/ai-visibility-audit", icon: "⌕", label: "AI Visibility Audit", desc: "12 checks for AI engine discoverability" },
  { href: "/seo-audit", icon: "✓", label: "SEO Audit", desc: "13-point SEO check with AI fixes" },
  { href: "/generate-product-description", icon: "✦", label: "Generate Product Description", desc: "AI-powered, SEO-ready in seconds" },
];

function NavBar() {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <>
      <nav className="landing-nav">
        {/* Left: Logo (desktop) / Hamburger (mobile) */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <button className="nav-hamburger" onClick={() => setMenuOpen(true)} aria-label="Open menu">
            <span /><span /><span />
          </button>
          <div className="nav-left-logo">
            <a href="/" style={{ textDecoration: 'none' }}>
              <img src="/logo.svg" alt="Dablin" height="44" />
            </a>
          </div>
        </div>

        {/* Center logo on mobile only */}
        <div className="nav-center-logo">
          <a href="/" style={{ textDecoration: 'none' }}>
            <img src="/logo.svg" alt="Dablin" height="40" />
          </a>
        </div>

        {/* Desktop: flat nav links */}
        <div className="landing-nav-links">
          <a href="/ai-visibility-check" className="nav-direct-link">AI Visibility Check</a>
          <a href="/ai-visibility-audit" className="nav-direct-link">AI Visibility Audit</a>
          <a href="/seo-audit" className="nav-direct-link">SEO Audit</a>
          <a href="/generate-product-description" className="nav-direct-link">Generate</a>
          <a href="/pricing" className="nav-direct-link">Pricing</a>
          <a href="https://blog.dablin.co" target="_blank" rel="noopener noreferrer" className="nav-direct-link">Blog</a>
        </div>

        {/* Right: Sign in + Sign up */}
        <div className="landing-nav-actions">
          <SignInButton mode="modal">
            <button className="btn-ghost">Sign in</button>
          </SignInButton>
          <div onClick={() => trackEvent('sign_up_modal_opened', { location: 'nav' })}>
            <SignUpButton mode="modal">
              <button className="btn-primary">Sign up</button>
            </SignUpButton>
          </div>
        </div>
      </nav>

      {/* Mobile full-screen menu */}
      <div className={`mobile-menu ${menuOpen ? 'open' : ''}`}>
        <div className="mobile-menu-header">
          <img src="/logo.svg" alt="Dablin" height="40" />
          <button className="mobile-menu-close" onClick={() => setMenuOpen(false)}>×</button>
        </div>
        {NAV_ITEMS.map(item => (
          <a key={item.href} href={item.href} className="mobile-menu-item" onClick={() => setMenuOpen(false)}>
            <span className="mobile-menu-icon">{item.icon}</span>
            <div>
              <div className="mobile-menu-label">{item.label}</div>
              <div className="mobile-menu-desc">{item.desc}</div>
            </div>
          </a>
        ))}
        <a href="/pricing" className="mobile-menu-item" onClick={() => setMenuOpen(false)}>
          <span className="mobile-menu-icon">€</span>
          <div>
            <div className="mobile-menu-label">Pricing</div>
            <div className="mobile-menu-desc">Pay per use, credits never expire</div>
          </div>
        </a>
        <a href="https://blog.dablin.co" target="_blank" rel="noopener noreferrer" className="mobile-menu-item" onClick={() => setMenuOpen(false)}>
          <span className="mobile-menu-icon">✍</span>
          <div>
            <div className="mobile-menu-label">Blog</div>
            <div className="mobile-menu-desc">AI visibility, GEO and SEO guides</div>
          </div>
        </a>
        <div className="mobile-menu-cta">
          <div onClick={() => { trackEvent('sign_up_modal_opened', { location: 'mobile_menu' }); setMenuOpen(false); }}>
            <SignUpButton mode="modal">
              <button className="btn-primary" style={{ width: '100%', padding: '14px', fontSize: '16px', borderRadius: '10px' }}>Sign up free</button>
            </SignUpButton>
          </div>
          <SignInButton mode="modal">
            <button className="btn-ghost" style={{ width: '100%', padding: '14px', fontSize: '16px', borderRadius: '10px' }} onClick={() => setMenuOpen(false)}>Sign in</button>
          </SignInButton>
        </div>
      </div>
    </>
  );
}

function HeroUrlForm() {
  const [url, setUrl] = useState('');

  function handleAnalyze() {
    if (!url.trim()) return;
    sessionStorage.setItem("postLoginRedirect", "/dashboard/seo-audit");
    sessionStorage.setItem("heroUrl", url.trim());
    window.location.href = "/dashboard/seo-audit";
  }

  return (
    <div className="hero-url-form">
      <input
        className="hero-url-input"
        type="url"
        placeholder="Enter your website URL"
        value={url}
        onChange={e => setUrl(e.target.value)}
        onKeyDown={e => e.key === "Enter" && handleAnalyze()}
      />
      <SignUpButton mode="modal" fallbackRedirectUrl="/dashboard/seo-audit">
        <button className="hero-url-btn" onClick={() => {
          sessionStorage.setItem("heroUrl", url.trim());
          trackEvent('hero_url_analyze_clicked', { url });
        }}>
          Analyze →
        </button>
      </SignUpButton>
    </div>
  );
}

export default function Landing() {
  return (
    <div className="landing">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&family=Roboto+Condensed:wght@700;800&display=swap');

        :root {
          --green: #2d7a3a; --green-light: #3d9e4e; --green-pale: #e8f5ea;
          --green-mid: #c8e6cb; --dark: #0f1a10; --dark-mid: #1a2e1c;
          --text: #1c2e1e; --muted: #5a7a5e; --border: #d4e8d6;
          --white: #ffffff; --off-white: #f7fbf7;
          --forest: #0d2116; --forest-mid: #122a1a;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        .landing { font-family: 'Roboto', sans-serif; color: var(--text); background: var(--white); min-height: 100vh; overflow-x: hidden; }

        /* NAV */
        .landing-nav { display: flex; align-items: center; justify-content: space-between; padding: 0 48px; height: 72px; position: sticky; top: 0; background: var(--forest); backdrop-filter: blur(12px); border-bottom: 1px solid rgba(255,255,255,0.08); z-index: 100; }
        .nav-brand img { display: block; }
        .landing-nav-links { display: flex; align-items: center; gap: 32px; }
        .nav-text-link { font-size: 15px; font-weight: 500; color: rgba(255,255,255,0.75); text-decoration: none; transition: color 0.2s; }
        .nav-text-link:hover { color: white; }
        .nav-direct-link { font-size: 15px; font-weight: 500; color: rgba(255,255,255,0.75); text-decoration: none; transition: color 0.2s; white-space: nowrap; }
        .nav-direct-link:hover { color: white; }
        .landing-nav-actions { display: flex; gap: 12px; align-items: center; }
        .btn-ghost { background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.15); color: rgba(255,255,255,0.85); padding: 10px 22px; border-radius: 8px; font-family: 'Roboto', sans-serif; font-size: 14px; cursor: pointer; transition: all 0.2s; }
        .btn-ghost:hover { background: rgba(255,255,255,0.14); color: white; }
        .btn-primary { background: white; color: var(--forest); border: none; padding: 10px 22px; border-radius: 8px; font-family: 'Roboto', sans-serif; font-size: 14px; font-weight: 600; cursor: pointer; transition: all 0.2s; }
        .btn-primary:hover { background: #e8f5ea; transform: translateY(-1px); }
        .btn-large { padding: 16px 36px; font-size: 16px; border-radius: 10px; font-weight: 600; }
        .btn-outline-green { background: none; border: 2px solid rgba(255,255,255,0.3); color: white; padding: 14px 32px; border-radius: 10px; font-family: 'Roboto', sans-serif; font-size: 16px; font-weight: 500; cursor: pointer; transition: all 0.2s; }
        .btn-outline-green:hover { border-color: white; background: rgba(255,255,255,0.08); }

        /* HAMBURGER */
        .nav-hamburger { display: none; background: none; border: 1px solid rgba(255,255,255,0.2); border-radius: 8px; padding: 8px 10px; cursor: pointer; flex-direction: column; gap: 4px; }
        .nav-hamburger span { display: block; width: 18px; height: 2px; background: white; border-radius: 2px; }
        .nav-center-logo { display: none; }
        .nav-left-logo { display: block; }
        .mobile-menu { display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: var(--forest); z-index: 500; padding: 24px; overflow-y: auto; }
        .mobile-menu.open { display: flex; flex-direction: column; }
        .mobile-menu-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; }
        .mobile-menu-close { background: none; border: none; font-size: 28px; color: white; cursor: pointer; line-height: 1; }
        .mobile-menu-item { display: flex; align-items: flex-start; gap: 14px; padding: 16px 0; border-bottom: 1px solid rgba(255,255,255,0.1); text-decoration: none; }
        .mobile-menu-item:last-child { border-bottom: none; }
        .mobile-menu-icon { font-size: 20px; color: var(--green-light); flex-shrink: 0; margin-top: 2px; }
        .mobile-menu-label { font-size: 16px; font-weight: 600; color: white; margin-bottom: 3px; }
        .mobile-menu-desc { font-size: 13px; color: rgba(255,255,255,0.5); }
        .mobile-menu-cta { margin-top: 24px; display: flex; flex-direction: column; gap: 12px; }

        /* HERO */
        .hero { background: var(--forest); max-width: 100%; padding: 80px 48px 96px; text-align: center; }
        .hero-title { font-family: 'Roboto Condensed', sans-serif; font-size: clamp(44px, 7vw, 80px); font-weight: 800; line-height: 1.0; letter-spacing: -2.5px; color: white; margin-bottom: 24px; }
        .hero-accent { color: #6fcf8a; }
        .hero-sub { font-size: 19px; color: rgba(255,255,255,0.6); max-width: 580px; margin: 0 auto 12px; line-height: 1.65; font-weight: 300; }
        .hero-actions { display: flex; flex-direction: column; align-items: center; gap: 12px; margin-bottom: 48px; }
        .hero-note { font-size: 13px; color: rgba(255,255,255,0.4); }

        /* URL INPUT FIELD */
        .hero-url-form { display: flex; align-items: center; max-width: 580px; margin: 40px auto 16px; background: white; border-radius: 100px; padding: 6px 6px 6px 24px; box-shadow: 0 8px 40px rgba(0,0,0,0.3); }
        .hero-url-input { flex: 1; border: none; outline: none; font-size: 15px; font-family: 'Roboto', sans-serif; color: var(--dark); background: transparent; }
        .hero-url-input::placeholder { color: #9ab09c; }
        .hero-url-btn { background: var(--forest); color: white; border: none; border-radius: 100px; padding: 12px 28px; font-size: 15px; font-weight: 600; cursor: pointer; transition: all 0.2s; white-space: nowrap; font-family: 'Roboto', sans-serif; }
        .hero-url-btn:hover { background: #1a3a22; }

        /* SCREENSHOT SECTION */
        .screenshot-section { background: var(--dark); padding: 32px 48px; text-align: center; }
        .section-label { font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 1.5px; color: var(--green-light); margin-bottom: 16px; }
        .section-title { font-family: 'Roboto Condensed', sans-serif; font-size: clamp(28px, 4vw, 44px); font-weight: 700; color: white; margin-bottom: 16px; letter-spacing: -1px; }
        .section-sub { font-size: 16px; color: rgba(255,255,255,0.5); max-width: 600px; margin: 0 auto; line-height: 1.6; }

        /* FEATURES */
        .features-section { padding: 80px 48px; max-width: 1100px; margin: 0 auto; }
        .features-header { text-align: center; margin-bottom: 56px; }
        .section-title-dark { font-family: 'Roboto Condensed', sans-serif; font-size: clamp(28px, 4vw, 44px); font-weight: 700; color: var(--dark); margin-bottom: 16px; letter-spacing: -1px; }
        .section-sub-dark { font-size: 16px; color: var(--muted); max-width: 520px; margin: 0 auto; line-height: 1.6; }
        .features-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; }
        .feature-card { background: var(--off-white); border: 1px solid var(--border); border-radius: 12px; padding: 28px; transition: all 0.2s; }
        .feature-card:hover { border-color: var(--green-mid); box-shadow: 0 4px 20px rgba(45,122,58,0.08); transform: translateY(-2px); }
        .feature-title { font-family: 'Roboto Condensed', sans-serif; font-size: 16px; font-weight: 700; color: var(--dark); margin-bottom: 8px; }
        .feature-desc { font-size: 14px; color: var(--muted); line-height: 1.55; }

        /* PRICING */
        .pricing-section { padding: 80px 48px; max-width: 1100px; margin: 0 auto; }
        .pricing-header { text-align: center; margin-bottom: 48px; }
        .pricing-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; align-items: start; }
        .pricing-card { border: 1px solid var(--border); border-radius: 14px; padding: 28px; background: white; position: relative; transition: all 0.2s; min-width: 0; }
        .pricing-card:hover { box-shadow: 0 8px 32px rgba(45,122,58,0.1); transform: translateY(-2px); }
        .pricing-card.highlight { border-color: var(--green); border-width: 2px; background: var(--off-white); }
        .pricing-popular { position: absolute; top: -12px; left: 50%; transform: translateX(-50%); background: var(--green); color: white; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; padding: 4px 14px; border-radius: 100px; white-space: nowrap; }
        .pricing-name { font-family: 'Roboto Condensed', sans-serif; font-size: 15px; font-weight: 700; color: var(--dark); margin-bottom: 8px; }
        .pricing-price { font-family: 'Roboto Condensed', sans-serif; font-size: 36px; font-weight: 800; color: var(--dark); margin-bottom: 2px; }
        .pricing-credits { font-size: 13px; color: var(--green); font-weight: 600; margin-bottom: 4px; }
        .pricing-desc { font-size: 12px; color: var(--muted); margin-bottom: 20px; }
        .pricing-features { list-style: none; margin-bottom: 24px; display: flex; flex-direction: column; gap: 8px; }
        .pricing-features li { font-size: 13px; color: var(--text); display: flex; align-items: center; gap: 8px; }
        .pricing-features li::before { content: "✓"; color: var(--green); font-weight: 700; font-size: 12px; flex-shrink: 0; }
        .pricing-btn { width: 100%; padding: 11px; border-radius: 8px; font-family: 'Roboto', sans-serif; font-size: 14px; font-weight: 600; cursor: pointer; transition: all 0.2s; border: none; }
        .pricing-btn.primary { background: var(--green); color: white; }
        .pricing-btn.primary:hover { background: var(--green-light); }
        .pricing-btn.secondary { background: var(--off-white); color: var(--text); border: 1px solid var(--border); }
        .pricing-btn.secondary:hover { border-color: var(--green); color: var(--green); }

        /* FAQ */
        .faq-section { padding: 80px 48px; background: var(--white); }
        .faq-inner { max-width: 780px; margin: 0 auto; }
        .faq-list { display: flex; flex-direction: column; gap: 0; }
        .faq-item { border-bottom: 1px solid var(--border); padding: 20px 0; cursor: pointer; }
        .faq-item:first-child { border-top: 1px solid var(--border); }
        .faq-question { display: flex; justify-content: space-between; align-items: center; gap: 16px; font-size: 16px; font-weight: 600; color: var(--dark); }
        .faq-icon { font-size: 22px; color: var(--green); flex-shrink: 0; font-weight: 300; }
        .faq-answer { font-size: 15px; color: var(--muted); line-height: 1.65; margin-top: 12px; padding-right: 32px; }

        /* CTA */
        .cta-section { background: var(--dark); padding: 80px 48px; text-align: center; }
        .cta-title { font-family: 'Roboto Condensed', sans-serif; font-size: clamp(28px, 4vw, 48px); font-weight: 800; color: white; margin-bottom: 16px; letter-spacing: -1.5px; }
        .cta-title span { color: var(--green-light); }
        .cta-sub { font-size: 17px; color: rgba(255,255,255,0.5); margin-bottom: 36px; line-height: 1.6; }
        .cta-actions { display: flex; align-items: center; justify-content: center; gap: 16px; }

        /* FOOTER */
        .landing-footer { background: var(--dark-mid); padding: 32px 48px; display: flex; align-items: center; justify-content: space-between; border-top: 1px solid rgba(255,255,255,0.06); }
        .footer-copy { font-size: 13px; color: rgba(255,255,255,0.3); }
        .footer-links { display: flex; gap: 24px; }
        .footer-links a { font-size: 13px; color: rgba(255,255,255,0.3); text-decoration: none; }
        .footer-links a:hover { color: rgba(255,255,255,0.7); }

        @media (max-width: 900px) {
          .landing-nav { padding: 0 20px; }
          .landing-nav-links { display: none; }
          .landing-nav-actions { display: none; }
          .nav-hamburger { display: flex; }
          .nav-left-logo { display: none; }
          .nav-center-logo { display: block; position: absolute; left: 50%; transform: translateX(-50%); }
          .hero { padding: 48px 20px 56px; }
          .hero-sub { font-size: 16px; }
          .hero-url-form { margin: 32px 0 16px; flex-direction: column; border-radius: 14px; padding: 12px; gap: 8px; }
          .hero-url-input { font-size: 14px; }
          .hero-url-btn { width: 100%; border-radius: 8px; }
          .features-grid { grid-template-columns: 1fr; }
          .pricing-grid { grid-template-columns: 1fr; gap: 16px; }
          .features-section, .pricing-section, .cta-section, .faq-section { padding: 48px 20px; }
          .screenshot-section { padding: 40px 20px; }
          .landing-footer { padding: 24px 20px; flex-direction: column; gap: 16px; text-align: center; }
          .cta-actions { flex-direction: column; }
          .faq-answer { padding-right: 0; }
        }
      `}</style>

      {/* NAV */}
      <NavBar />

      {/* HERO */}
      <div className="hero">
        <h1 className="hero-title">
          Be visible everywhere<br />
          <span className="hero-accent">search happens.</span>
        </h1>
        <p className="hero-sub">
          Capture visibility across Google and AI — all with one platform built for today's search.
        </p>

        {/* URL INPUT FIELD */}
        <HeroUrlForm />
      </div>

      {/* VIDEO SECTION */}
      <div style={{ background: '#f7fbf7', padding: '56px 40px', textAlign: 'center', borderTop: '1px solid #d4e8d6' }}>
        <p style={{ fontSize: '11px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '1.5px', color: '#3d9e4e', marginBottom: '14px' }}>See it in action</p>
        <h2 style={{ fontSize: '36px', fontWeight: '800', color: '#0f1a10', letterSpacing: '-1px', marginBottom: '12px' }}>Everything your pages need</h2>
        <p style={{ fontSize: '16px', color: '#5a7a5e', maxWidth: '500px', margin: '0 auto 40px', lineHeight: '1.6' }}>
          From SEO audits to AI visibility checks — Dablin covers it all in one place.
        </p>
        <div style={{ maxWidth: '860px', margin: '0 auto', background: '#0d2116', borderRadius: '16px', overflow: 'hidden', border: '1px solid #1a3a22' }}>
          <div style={{ background: '#122a1a', padding: '10px 16px', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
            <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#ff5f57' }} />
            <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#febc2e' }} />
            <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#28c840' }} />
            <span style={{ flex: 1, textAlign: 'center', fontSize: '12px', color: 'rgba(255,255,255,0.3)' }}>dablin.co</span>
          </div>
          {/* SWAP src WITH YOUR YOUTUBE/VIMEO EMBED URL WHEN READY */}
          {/* Example YouTube: src="https://www.youtube.com/embed/YOUR_VIDEO_ID" */}
          {/* Example Vimeo:   src="https://player.vimeo.com/video/YOUR_VIDEO_ID" */}
          <iframe
            src="https://www.youtube.com/embed/pHVILT29ElE?rel=0&modestbranding=1"
            style={{ width: '100%', aspectRatio: '16/9', border: 'none', display: 'block' }}
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>
      </div>

      {/* FAQ */}
      <div className="faq-section">
        <div className="faq-inner">
          <div className="features-header">
            <p className="section-label" style={{color:'var(--green)'}}>FAQ</p>
            <h2 className="section-title-dark">Common questions</h2>
          </div>
          <div className="faq-list">
            {FAQ.map((item, i) => (
              <FaqItem key={i} q={item.q} a={item.a} />
            ))}
          </div>
        </div>
      </div>

      {/* CTA */}
      <div className="cta-section">
        <h2 className="cta-title">Generate. Audit. <span>Get found.</span></h2>
        <p className="cta-sub">The only e-commerce tool that writes copy, fixes SEO, and optimises for AI engines — no subscription, no monthly fees.</p>
        <div className="cta-actions">
          <div onClick={() => trackEvent('sign_up_modal_opened', { location: 'cta_bottom' })}>
            <SignUpButton mode="modal">
              <button className="btn-primary btn-large">Start free — no card needed</button>
            </SignUpButton>
          </div>
          <SignInButton mode="modal">
            <button className="btn-outline-green">Sign in</button>
          </SignInButton>
        </div>
      </div>

      {/* FOOTER */}
      <footer className="landing-footer">
        <div className="footer-copy">© 2026 Dablin. All rights reserved.</div>
        <div className="footer-links">
          <a href="/legal.html">Privacy</a>
          <a href="/legal.html">Terms</a>
          <a href="mailto:hello@dablin.co">Contact us: hello@dablin.co</a>
        </div>
      </footer>
    </div>
  );
}
